// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://mpnnthalbitzyilsqitb.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1wbm50aGFsYml0enlpbHNxaXRiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MTkyNzU1NjMsImV4cCI6MjAzNDg1MTU2M30.HVFdEJhX_wfIlpcCumgOOM3qPGFQwc2dhJZaTh8ar54";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);